import Foundation
import OysterMobile

/// Thin Swift wrapper over the gomobile-bound `wallet/mobile` Go package
/// (`OysterMobile.xcframework`). Keeps the FFI surface in one place so the rest
/// of the app never touches the `Mobile*` C symbols directly.
///
/// Today this exposes the canonical BIP39 primitives (generate/validate) so
/// onboarding uses the *same* library the Go wallet uses. Address derivation,
/// balance and signing arrive with the in-process node (Start/OfflineSign) in
/// M3/M4 — see apps/pearl-native/PLAN.md §4.
enum OysterBridge {
    /// `true` if the embedded Go framework is reachable across the FFI.
    static func isAvailable() -> Bool { MobilePing() == "pearl-mobile ok" }

    /// A fresh 12-word BIP39 mnemonic generated by go-bip39 (128-bit entropy).
    static func generateMnemonic() -> String? {
        var error: NSError?
        let m = MobileGenerateMnemonic(&error)
        return error == nil && !m.isEmpty ? m : nil
    }

    /// A fresh 24-word BIP39 mnemonic (256-bit entropy).
    static func generateMnemonic24() -> String? {
        var error: NSError?
        let m = MobileGenerateMnemonic24(&error)
        return error == nil && !m.isEmpty ? m : nil
    }

    /// Validates a BIP39 mnemonic (wordlist + checksum) via go-bip39.
    static func validate(_ mnemonic: String) -> Bool {
        MobileValidateMnemonic(mnemonic.trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased())
    }

    /// The taproot receive address at a given external index (0,1,2…). Creates the
    /// local wallet db under `dataDir` on first use. Every index shares the same
    /// account xpub, so balance/history/UTXOs and signing already cover funds on
    /// any of them. Blocking + disk I/O — call off the main actor.
    ///
    /// Deliberately the ONLY address API exposed: the no-index `MobileReceiveAddress`
    /// is stateful — after the db derives other keys it stops returning index 0 and
    /// can hand out INTERNAL-chain addresses (verified in tools/recover/addr-test.swift),
    /// which the external-only xpub scan can't see. Never wrap it again.
    static func receiveAddress(mnemonic: String, dataDir: String, network: String, at index: Int) -> String? {
        var error: NSError?
        let addr = MobileReceiveAddressAt(mnemonic, dataDir, network, index, &error)
        return error == nil && !addr.isEmpty ? addr : nil
    }

    /// The BIP86 account xpub (for Blockbook xpub aggregation). Blocking I/O.
    static func accountXpub(mnemonic: String, dataDir: String, network: String) -> String? {
        var error: NSError?
        let x = MobileAccountXpub(mnemonic, dataDir, network, &error)
        return error == nil && !x.isEmpty ? x : nil
    }

    /// Build + sign (taproot, on-device) a payment. Returns the raw signed tx hex
    /// ready to broadcast, or throws. Blocking + disk I/O — call off the main actor.
    static func buildSignedTx(mnemonic: String, dataDir: String, network: String,
                              to: String, amountSat: Int64, feeSatPerKB: Int64,
                              utxosJSON: String) throws -> String {
        var error: NSError?
        let hex = MobileBuildSignedTx(mnemonic, dataDir, network, to, amountSat, feeSatPerKB, utxosJSON, &error)
        if let error { throw error }
        return hex
    }
}

/// Serializes ALL on-disk wallet-DB access (derivation / xpub / signing) through a
/// single actor so concurrent derivation and signing never contend on the same
/// `wallet.db` file. The Go/bbolt store already takes an OS flock, but funnelling
/// the blocking FFI calls through here keeps the contention on the Swift side (no
/// blocked flock waits) and off the main actor.
actor WalletDBQueue {
    static let shared = WalletDBQueue()
    func run<T: Sendable>(_ work: @Sendable () throws -> T) rethrows -> T {
        try work()
    }
}
